### PR TITLE
Issue #108 Fix tooltip formatter

### PR DESCRIPTION
**Pull request by sovattha**
As described in the issue, this is the fix of the broken formatter.
Cheers!

### CODE REVIEW

**Comment by seiyria** [comment]
Thanks!

**Comment by JulianWielga** [comment]
this is so wrong, see example:
http://codepen.io/JulianWielga/pen/RWmQeO - after this "fix"
http://codepen.io/JulianWielga/pen/Yybazb - before this "fix" and after my already merged patch

see https://docs.angularjs.org/api/ng/service/$compile - scope: &attr

**Comment by seiyria** [comment]
Then please feel free to add some tests so this doesn't happen.

**Comment by JulianWielga** [comment]
in #105 i've corrected test.html to use "formatterFn(value)" notation.
there were no other docs/tests containing formatter.

**Comment by seiyria** [comment]
Correct, that's because there is no testing. I either have to merge everything that looks ok, or merge nothing, because I don't really have the time to maintain this project. As such, I generally just merge everything that doesn't appear to break anything (which is hard to ascertain without unit tests). I don't use this particular library anymore so I have no incentive to maintain it besides doing so to be helpful, and unless someone wants to step up, that's unfortunately how it will be.

**Comment by JulianWielga** [comment]
made pull request #113 with first e2e test and revert to formatter format where we need value in expression.

**Pull request merged**
