### PR TITLE
change the require string

### PR DESCRIPTION
**Pull request by super-ienien**
It should be this nomenclature to load properly with a tool like require.js

### CODE REVIEW

**Comment by seiyria** [comment]
I'm going to need to see an example because I have no idea what this is, does, or means.

**Comment by super-ienien** [comment]
it require the 'bootstrap-slider' module as you named it in npm

**Comment by seiyria** [comment]
Yeah, but I imagine it depends on what require is requiring from - bootstrap-slider exports to module.bootstrapSlider or window.bootstrapSlider. I don't know enough about this to say either way which is correct.

**Comment by super-ienien** [comment]
In the case of require js, this is not very relevant. But in the case of browserify it load the bootstrap-slider module based on the name inside package.json. So 'boostrapSlider' doesn't work with browserify

**Pull request merged**
