### PR TITLE
Slider events not being called

### PR DESCRIPTION
**Pull request by david-hollifield**
Slider events defined as attributes were not being called. Updated
invoker function with proper signature.

### CODE REVIEW

**Comment by seiyria** [comment]
Thanks!

**Comment by hmillet** [comment]
@david-hollifield @seiyria :+1: 
Hi ! I've got a problem with this commit.

The fact that event name are in full lowercase (`onstartslide' instead of `onStartSlide`) make events no more working

Why did you do this ? Can we revert ?

**Comment by hmillet** [comment]
In fact, we must aggree and write a small documentation for the usage of events.

In `test.html`, we can find :

```js
          on-slide="slideDelegate(value, $event)"
```

`on-slide` or `onslide` ?
`slideDelegate(value, $event)` or `slideDelegate($event, value)`  or `slideDelegate` ?

**Comment by seiyria** [comment]
I'm fine with some better documentation. Really, this was a quick job to get something working, but then people started using it, haha.

**Comment by hmillet** [comment]
I understand ;-)

It was a good and useful work for people....

Just choose the syntax, I'll write the doc (and upgrade code if necessary)

**Comment by seiyria** [comment]
If you could follow the style of bootstrap-slider, that would be for the best. People will be familiar enough with that, I think.

**Comment by david-hollifield** [comment]
Fixed in pull request #70

**Comment by hmillet** [comment]
thanks for the fix

So we are agree we will use `on-slide`, `on-start-slide`, `on-stop-slide` attributes

**Comment by david-hollifield** [comment]
No problem. Using the non dashed versions was just a brain fart.

**Comment by seiyria** [comment]
Thank you!

**Pull request merged**
