### PR TITLE
Update Bower dependencies

### PR DESCRIPTION
**Pull request by sovattha**
I guess it works pretty well so far

### CODE REVIEW

**Comment by seiyria** [comment]
Is there a reason you removed the `||` in the angular dependency?

**Comment by sovattha** [comment]
No special reason. I agree we could keep them.

**Comment by seiyria** [comment]
Please update to match and I'll accept this.

**Comment by sovattha** [comment]
Here it is

**Comment by seiyria** [comment]
thanks.

**Comment by sovattha** [comment]
Cool :) 
Maybe the change is too light for a new release? I'd like to bower install it in my project.

**Comment by seiyria** [comment]
tagged as 0.1.19

**Comment by sovattha** [comment]
You rock man! Works like a charm

**Pull request merged**
