### PR TITLE
Bumped seiyria-bootstrap-slider dependency

### PR DESCRIPTION
**Pull request by jessertaylor**
Enables newer version to be installed via bower with new features like the tooltip position

### CODE REVIEW

**Comment by jessertaylor** [comment]
@seiyria I've semi tested it - seems OK. Hopefully this will mean I can just do a 

```
bower install angular-bootstrap-slider --save
```

Which will give me the latest version of seiyria-bootstrap-slider which has the tooltip position feature.

**Comment by seiyria** [comment]
Thanks for this!

**Comment by jessertaylor** [comment]
No problem, cheers for the directive. :+1:

**Comment by jessertaylor** [comment]
@seiyria Sorry to be a pain would it be possible to do a release with the updated bower dependency? Means I can installed via bower pain-free :dancer:

**Comment by seiyria** [comment]
Sure, I'll do that now. It'll be 0.1.17.

**Comment by jessertaylor** [comment]
It's working now - many thanks!

**Comment by seiyria** [comment]
Thank you too!

**Pull request merged**
