### PR TITLE
Using scope properties for event handlers

### PR DESCRIPTION
**Pull request by santam85**
Using the defined scope properties for event handlers instead of parsing attributes.
Parsing string values from ng-model as it is already done for value attribute
Better and more angular friendly way of defining listeners", eg:

`ng-model="value" on-slide-stop="refresh(value)"`

### CODE REVIEW

**Comment by seiyria** [comment]
I've seen people put the ngDisabled watcher on different scopes (see #60 and #69) and I'm not sure I want to keep going back and forth, so could you explain why you're doing it this way?

**Comment by santam85** [comment]
Honestly, I just pulled the latest version and went with that.
As #69 is stating, we should watch on the isolated scope. It is working correctly for me right now, so I don't think #60 is valid.

**Comment by seiyria** [comment]
Is it possible that the two are angular version-dependent? I know when I swapped angular versions from 1.2.x to 1.3.x I had some slight differences. If that is the case, what version of angular are you using? 1.3.15 or greater?

**Comment by santam85** [comment]
Very possible that's the case, I am on angular 1.4

**Comment by seiyria** [comment]
I will accept this then, and I'll consider it done.

**Pull request merged**
